title: Alexander Jarrett Engineering Portfolio
description: This is a repository of the large engineering projects I have completed throughout my academic career.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
